### ISSUE TITLE
[Feature Request] Attachment extensions

### ISSUE THREAD

**Issue by chenmaoran** [husjon/obsidian-file-cleaner-redux#28]
If "Attachment extensions" is empty, then all attachments with extensions other than .md should be processed.

**Comment by husjon** [comment]
I don't think this would be the best way of handling that since it would make it so that if someone wants to only clean up markdown files there would be no real way of doing that.

Instead, I'll add support for the `.*` wildcard in **Attachment extensions**, this will make it so that it target all attachments if one wants that.
