### ISSUE TITLE
.excalidraw.md files are not deleted + feature ideas

### ISSUE THREAD

**Issue by Iphinis** [husjon/obsidian-file-cleaner-redux#61]
Hello, 

Is it normal that .excalidraw.md files aren't deleted with .* and even with .excalidraw.md or .excalidraw.* ?

I also tried \*.excalidraw.* and *.excalidraw.md but those seems to be incorrect expressions (they are deleted instantly when I close the settings panel). Maybe it is because it ends with ".md" ? (that expression doesn't work either, thankfully ahah, for security reasons I suppose)

Also I have an idea, when the deleting prompt appears it would be nice if we could check for each file (or even folder) whether we delete it.

Another little thing is that it would be nice in the setting panel if the textbox had a min-width (according to its content, or not, as you wish).

Thanks in advance.

**Comment by husjon** [comment]
Hmm this might be because of the `.md` suffix which might make it so that the plugin assumes that is is a normal markdown file and does not do further processing (other than the file being completely empty).
I'll need to look into this further.

As for the file extensions you tried, I think you should have tried the following: `.excalidraw.* and .excalidraw.md`, as in omitting the initial `*`.

Regarding the check for each file (and/or folder) to be deleted, do you mean just inspection or to select if they should be deleted or not as in a checkbox, if so this is in the works (however taking some time) with the following issue #58 

As for textbox min-width in settings, this I agree with wholly.

**Comment by Iphinis** [comment]
Yup, I think I have already tried it when I opened the issue but I didn't want to bother writing all my tests.
To be sure I just did it right now and it doesn't work.

Yes something like a checkbox for each element! Because when I clear my files there could be a situation where I don't want to remove a certain file right now.
Furthermore, you could also create an option to ignore certain files (as you did for folders), and in addition creating a button next to the checkbox and the file/folder name to add it to the ignored list (when the user wants to clear the vault).

Thank you very much for considering my suggestions! Implement them if you wish and perhaps gradually ;)

**Comment by husjon** [comment]
So, I've had a look at why the excalidraw files are not deleted.
They do use their own format, however it does follow markdown standard so it is possible to parse and determine if they are empty or not.

My main issue is that Excalidraw by default compresses the files to make the drawings take less space (not a bad thing at all it just complicates things), this seem to use an external library which I kinda do not want to include in this plugin for this one specific case.
What I am however thinking off is to make it possible so that if the Excalidraw files are not compressed (which can be toggled in Excalidraws settings), I can clean them up by inspecting the content and verify that they are empty.

This will unfortunately take a bit of time to get it working.
However with the rewrite I did back in June will make it a bit easier as I did make it possible to further inspection code blocks etc (which Excalidraw uses to contain the drawing data).

As for the size of the text boxes, I have prepared a fix and will be releasing it shortly (#63), they will now be resizable within a certain range and wont freak out like before. :)

**Comment by husjon** [comment]
Hi @Iphinis, I have now prepared a pull request to add support for Excalidraw files (see #66).
As mentioned in my previous comment, this will require the user to disable compression in Excalidraw.

**Comment by husjon** [comment]
I think the issue you're talking about is what is mentioned in #68
If I understand it correctly excalidraw files should have been handled like attachments instead of how they are now, is that correct?

If so, please also leave a comment in the mentioned issue above so I can track it there. :)
